### ISSUE TITLE
aws 서버 구축

### ISSUE THREAD

**Issue by Ernest45** [E24I/TOGEDOG#3]
### 설명 : aws 서버 세팅
***

해야할 일 목록
===
- [x] ec2 생성
- [x] rds 설정
- [x] CI/CD
- [x] S3 버켓
- [x] Actions Secret 설정
***

마감기한
===
11월 07일
***

참고 링크
===
[회의록](https://docs.google.com/document/d/1_ZOe7U8X3mhXRZShwYTL27KHezpylg8VCMgkscwD3bQ/edit?usp=sharing)
[관련문서](https://docs.google.com/spreadsheets/d/1nsAUPvQQuYzXSgecFxTp9rqCTH9UdODJ7tgKv6iSnZA/edit#gid=0)

**Comment by leesaewoo** [comment]
ec2: docker 설치, 메모리 스왑
rds: MySQL 20G , 추정 과금액 21$/month
S3: 기존에 사용하던 버킷 사용
